export { default as BasedTemplate } from '../components/templates/Base';
export { default as Home } from './Home';
export { default as Join } from './Join';
export { default as LearnMyself } from './LearnMyself';
export { default as Login } from './Login';
export { default as MyPage } from './MyPage';
export { default as Notice } from './Notice';
export { default as Setting } from './Setting';
export { default as ShareTogether } from './ShareTogether';
